services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex
    network_mode: bridge
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Havana
      - VERSION=docker
      #- PLEX_CLAIM= #optional
    ports:
      # https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/
      # The ports are for Plex services I don't necessarily need, so they are disabled for now.
      # - "1900:1900/udp" # (for access to the Plex DLNA Server)
      - "32400:32400" # (for access to the Plex Media Server) [required]
      # - "3005:3005" # (for controlling Plex Home Theater via Plex Companion)
      # - "32410:32410/udp" # (for current GDM network discovery)
      # - "32412:32412/udp" # (for current GDM network discovery)
      # - "32413:32413/udp" # (for current GDM network discovery)
      # - "32414:32414/udp" # (for current GDM network discovery)
      # - "32469:32469" # (for access to the Plex DLNA Server)
    volumes:
      - ./config:/config

      - e:/movies:/media/movies:ro
      - f:/movies:/media/movies1:ro
      
      - e:/tvshows:/media/tvshows:ro
      - f:/tvshows:/media/tvshows1:ro

      - f:/music:/media/music:ro
      - e:/youtube:/media/videos:ro