services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Havana
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /config:/app/config
    restart: unless-stopped
